### ISSUE TITLE
bfuse: short kernel write

### ISSUE THREAD

**Issue by nyaxt** [nyaxt/otaru#22]
```
2015/08/13 08:53:27 D [bfuse] main.go:93: short kernel write: written=16/4112 error="" stack=
goroutine 3596 [running]:
bazil.org/fuse.stack(0x0, 0x0)
	/Users/kouhei/go/src/github.com/nyaxt/otaru/Godeps/_workspace/src/bazil.org/fuse/debug.go:9 +0x84
bazil.org/fuse.(*Conn).writeToKernel(0xc2083c1080, 0xc215c36000, 0x1010, 0x1010, 0x0, 0x0)
	/Users/kouhei/go/src/github.com/nyaxt/otaru/Godeps/_workspace/src/bazil.org/fuse/fuse.go:1045 +0x15f
bazil.org/fuse.(*Conn).respond(0xc2083c1080, 0xc215c36000, 0x1010, 0x1010)
	/Users/kouhei/go/src/github.com/nyaxt/otaru/Godeps/_workspace/src/bazil.org/fuse/fuse.go:1052 +0x55
bazil.org/fuse.(*Header).respond(0xc2160c49a0, 0xc215c36000, 0x1010, 0x1010)
	/Users/kouhei/go/src/github.com/nyaxt/otaru/Godeps/_workspace/src/bazil.org/fuse/fuse.go:278 +0x5d
bazil.org/fuse.(*ReadRequest).Respond(0xc2160c49a0, 0xc216233360)
	/Users/kouhei/go/src/github.com/nyaxt/otaru/Godeps/_workspace/src/bazil.org/fuse/fuse.go:1686 +0x16f
bazil.org/fuse/fs.(*Server).serve(0xc2082be000, 0xb3b238, 0xc2160c49a0)
	/Users/kouhei/go/src/github.com/nyaxt/otaru/Godeps/_workspace/src/bazil.org/fuse/

**Comment by nyaxt** [comment]
resolved in up to date bfuse?
